project:
  type: website
  output-dir: docs

website:
  title: "Zaara Faruqui"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog/my-first-post.qmd
        text: Blog

collections:
  blog:
    type: posts
    path: blog
    sort: date

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true